---
- name: Include OS vars
  include_vars:
    "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"

- name: Installiere Pakete
  ansible.builtin.apt:
    deb: "{{ checkmk_agent__package }}"
    state: "{{ checkmk_agent__package_state }}"
